---
- name: Refresh inventory
  ansible.builtin.meta: refresh_inventory

- name: Task 0 - Check access to App (HTTP GET should return 200)
  ansible.builtin.uri:
    url: "http://{{ app_ip }}:{{ app_port }}/api/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 6
  delay: 30
  tags: ["test_dgc_access"]

- name: Task 1 - Login as a Notifier to get a DGC
  ansible.builtin.uri:
    url: "http://{{ app_ip }}:{{ app_port }}/api/auth/login/"
    method: POST
    body:
      email: "{{ app_notifier_email }}"
      password: "{{ app_notifier_password }}"
    body_format: json
    return_content: true
    status_code: 200
    headers:
      Cache-Control: no-cache
      Content-Type: "application/json; charset=UTF-8"
    validate_certs: false
  register: notifier_login
  until: notifier_login.status == 200
  retries: 6
  delay: 10
  tags: ["test_dgc_access"]

- name: Task 2 - Get Recovery DGC (should return {{ result_code }})
  ansible.builtin.uri:
    url: "http://{{ app_ip }}:{{ app_port }}/api/certificates/{{ dgc_uvci }}"
    method: GET
    body_format: json
    return_content: true
    status_code: "{{ result_code }}"
    headers:
      Cache-Control: no-cache
      Content-Type: "application/json; charset=UTF-8"
      Authorization: "Bearer {{ notifier_login.json.access }}"
  register: result
  until: result.status == result_code
  retries: 5
  delay: 10
  tags: ["test_dgc_access"]