export const defaultCountryCode = 'pt'

export const countries = {
  ad: { label: 'Andorra', phone: '376' },
  ae: { label: 'United Arab Emirates', phone: '971' },
  af: { label: 'Afghanistan', phone: '93' },
  ag: { label: 'Antigua and Barbuda', phone: '1-268' },
  ai: { label: 'Anguilla', phone: '1-264' },
  al: { label: 'Albania', phone: '355' },
  am: { label: 'Armenia', phone: '374' },
  ao: { label: 'Angola', phone: '244' },
  aq: { label: 'Antarctica', phone: '672' },
  ar: { label: 'Argentina', phone: '54' },
  as: { label: 'American Samoa', phone: '1-684' },
  at: { label: 'Austria', phone: '43' },
  au: { label: 'Australia', phone: '61' },
  aw: { label: 'Aruba', phone: '297' },
  ax: { label: 'Alland Islands', phone: '358' },
  az: { label: 'Azerbaijan', phone: '994' },
  ba: { label: 'Bosnia and Herzegovina', phone: '387' },
  bb: { label: 'Barbados', phone: '1-246' },
  bd: { label: 'Bangladesh', phone: '880' },
  be: { label: 'Belgium', phone: '32' },
  bf: { label: 'Burkina Faso', phone: '226' },
  bg: { label: 'Bulgaria', phone: '359' },
  bh: { label: 'Bahrain', phone: '973' },
  bi: { label: 'Burundi', phone: '257' },
  bj: { label: 'Benin', phone: '229' },
  bl: { label: 'Saint Barthelemy', phone: '590' },
  bm: { label: 'Bermuda', phone: '1-441' },
  bn: { label: 'Brunei Darussalam', phone: '673' },
  bo: { label: 'Bolivia', phone: '591' },
  br: { label: 'Brazil', phone: '55' },
  bs: { label: 'Bahamas', phone: '1-242' },
  bt: { label: 'Bhutan', phone: '975' },
  bv: { label: 'Bouvet Island', phone: '47' },
  bw: { label: 'Botswana', phone: '267' },
  by: { label: 'Belarus', phone: '375' },
  bz: { label: 'Belize', phone: '501' },
  ca: { label: 'Canada', phone: '1' },
  cc: { label: 'Cocos (Keeling) Islands', phone: '61' },
  cd: { label: 'Congo, Democratic Republic of the', phone: '243' },
  cf: { label: 'Central African Republic', phone: '236' },
  cg: { label: 'Congo, Republic of the', phone: '242' },
  ch: { label: 'Switzerland', phone: '41' },
  ci: { label: "Cote d'Ivoire", phone: '225' },
  ck: { label: 'Cook Islands', phone: '682' },
  cl: { label: 'Chile', phone: '56' },
  cm: { label: 'Cameroon', phone: '237' },
  cn: { label: 'China', phone: '86' },
  co: { label: 'Colombia', phone: '57' },
  cr: { label: 'Costa Rica', phone: '506' },
  cu: { label: 'Cuba', phone: '53' },
  cv: { label: 'Cape Verde', phone: '238' },
  cw: { label: 'Curacao', phone: '599' },
  cx: { label: 'Christmas Island', phone: '61' },
  cy: { label: 'Cyprus', phone: '357' },
  cz: { label: 'Czech Republic', phone: '420' },
  de: { label: 'Germany', phone: '49' },
  dj: { label: 'Djibouti', phone: '253' },
  dk: { label: 'Denmark', phone: '45' },
  dm: { label: 'Dominica', phone: '1-767' },
  do: { label: 'Dominican Republic', phone: '1-809' },
  dz: { label: 'Algeria', phone: '213' },
  ec: { label: 'Ecuador', phone: '593' },
  ee: { label: 'Estonia', phone: '372' },
  eg: { label: 'Egypt', phone: '20' },
  eh: { label: 'Western Sahara', phone: '212' },
  er: { label: 'Eritrea', phone: '291' },
  es: { label: 'Spain', phone: '34' },
  et: { label: 'Ethiopia', phone: '251' },
  fi: { label: 'Finland', phone: '358' },
  fj: { label: 'Fiji', phone: '679' },
  fk: { label: 'Falkland Islands (Malvinas)', phone: '500' },
  fm: { label: 'Micronesia, Federated States of', phone: '691' },
  fo: { label: 'Faroe Islands', phone: '298' },
  fr: { label: 'France', phone: '33' },
  ga: { label: 'Gabon', phone: '241' },
  gb: { label: 'United Kingdom', phone: '44' },
  gd: { label: 'Grenada', phone: '1-473' },
  ge: { label: 'Georgia', phone: '995' },
  gf: { label: 'French Guiana', phone: '594' },
  gg: { label: 'Guernsey', phone: '44' },
  gh: { label: 'Ghana', phone: '233' },
  gi: { label: 'Gibraltar', phone: '350' },
  gl: { label: 'Greenland', phone: '299' },
  gm: { label: 'Gambia', phone: '220' },
  gn: { label: 'Guinea', phone: '224' },
  gp: { label: 'Guadeloupe', phone: '590' },
  gq: { label: 'Equatorial Guinea', phone: '240' },
  gr: { label: 'Greece', phone: '30' },
  gs: { label: 'South Georgia and the South Sandwich Islands', phone: '500' },
  gt: { label: 'Guatemala', phone: '502' },
  gu: { label: 'Guam', phone: '1-671' },
  gw: { label: 'Guinea Bissau', phone: '245' },
  gy: { label: 'Guyana', phone: '592' },
  hk: { label: 'Hong Kong', phone: '852' },
  hm: { label: 'Heard Island and McDonald Islands', phone: '672' },
  hn: { label: 'Honduras', phone: '504' },
  hr: { label: 'Croatia', phone: '385' },
  ht: { label: 'Haiti', phone: '509' },
  hu: { label: 'Hungary', phone: '36' },
  id: { label: 'Indonesia', phone: '62' },
  ie: { label: 'Ireland', phone: '353' },
  il: { label: 'Israel', phone: '972' },
  im: { label: 'Isle of Man', phone: '44' },
  in: { label: 'India', phone: '91' },
  io: { label: 'British Indian Ocean Territory', phone: '246' },
  iq: { label: 'Iraq', phone: '964' },
  ir: { label: 'Iran, Islamic Republic of', phone: '98' },
  is: { label: 'Iceland', phone: '354' },
  it: { label: 'Italy', phone: '39' },
  je: { label: 'Jersey', phone: '44' },
  jm: { label: 'Jamaica', phone: '1-876' },
  jo: { label: 'Jordan', phone: '962' },
  jp: { label: 'Japan', phone: '81' },
  ke: { label: 'Kenya', phone: '254' },
  kg: { label: 'Kyrgyzstan', phone: '996' },
  kh: { label: 'Cambodia', phone: '855' },
  ki: { label: 'Kiribati', phone: '686' },
  km: { label: 'Comoros', phone: '269' },
  kn: { label: 'Saint Kitts and Nevis', phone: '1-869' },
  kp: { label: "Korea, Democratic People's Republic of", phone: '850' },
  kr: { label: 'Korea, Republic of', phone: '82' },
  kw: { label: 'Kuwait', phone: '965' },
  ky: { label: 'Cayman Islands', phone: '1-345' },
  kz: { label: 'Kazakhstan', phone: '7' },
  la: { label: "Lao People's Democratic Republic", phone: '856' },
  lb: { label: 'Lebanon', phone: '961' },
  lc: { label: 'Saint Lucia', phone: '1-758' },
  li: { label: 'Liechtenstein', phone: '423' },
  lk: { label: 'Sri Lanka', phone: '94' },
  lr: { label: 'Liberia', phone: '231' },
  ls: { label: 'Lesotho', phone: '266' },
  lt: { label: 'Lithuania', phone: '370' },
  lu: { label: 'Luxembourg', phone: '352' },
  lv: { label: 'Latvia', phone: '371' },
  ly: { label: 'Libya', phone: '218' },
  ma: { label: 'Morocco', phone: '212' },
  mc: { label: 'Monaco', phone: '377' },
  md: { label: 'Moldova, Republic of', phone: '373' },
  me: { label: 'Montenegro', phone: '382' },
  mf: { label: 'Saint Martin (French part)', phone: '590' },
  mg: { label: 'Madagascar', phone: '261' },
  mh: { label: 'Marshall Islands', phone: '692' },
  mk: { label: 'Macedonia, the Former Yugoslav Republic of', phone: '389' },
  ml: { label: 'Mali', phone: '223' },
  mm: { label: 'Myanmar', phone: '95' },
  mn: { label: 'Mongolia', phone: '976' },
  mo: { label: 'Macao', phone: '853' },
  mp: { label: 'Northern Mariana Islands', phone: '1-670' },
  mq: { label: 'Martinique', phone: '596' },
  mr: { label: 'Mauritania', phone: '222' },
  ms: { label: 'Montserrat', phone: '1-664' },
  mt: { label: 'Malta', phone: '356' },
  mu: { label: 'Mauritius', phone: '230' },
  mv: { label: 'Maldives', phone: '960' },
  mw: { label: 'Malawi', phone: '265' },
  mx: { label: 'Mexico', phone: '52' },
  my: { label: 'Malaysia', phone: '60' },
  mz: { label: 'Mozambique', phone: '258' },
  na: { label: 'Namibia', phone: '264' },
  nc: { label: 'New Caledonia', phone: '687' },
  ne: { label: 'Niger', phone: '227' },
  nf: { label: 'Norfolk Island', phone: '672' },
  ng: { label: 'Nigeria', phone: '234' },
  ni: { label: 'Nicaragua', phone: '505' },
  nl: { label: 'Netherlands', phone: '31' },
  no: { label: 'Norway', phone: '47' },
  np: { label: 'Nepal', phone: '977' },
  nr: { label: 'Nauru', phone: '674' },
  nu: { label: 'Niue', phone: '683' },
  nz: { label: 'New Zealand', phone: '64' },
  om: { label: 'Oman', phone: '968' },
  pa: { label: 'Panama', phone: '507' },
  pe: { label: 'Peru', phone: '51' },
  pf: { label: 'French Polynesia', phone: '689' },
  pg: { label: 'Papua New Guinea', phone: '675' },
  ph: { label: 'Philippines', phone: '63' },
  pk: { label: 'Pakistan', phone: '92' },
  pl: { label: 'Poland', phone: '48' },
  pm: { label: 'Saint Pierre and Miquelon', phone: '508' },
  pn: { label: 'Pitcairn', phone: '870' },
  pr: { label: 'Puerto Rico', phone: '1' },
  ps: { label: 'Palestine, State of', phone: '970' },
  pt: { label: 'Portugal', phone: '351' },
  pw: { label: 'Palau', phone: '680' },
  py: { label: 'Paraguay', phone: '595' },
  qa: { label: 'Qatar', phone: '974' },
  re: { label: 'Reunion', phone: '262' },
  ro: { label: 'Romania', phone: '40' },
  rs: { label: 'Serbia', phone: '381' },
  ru: { label: 'Russian Federation', phone: '7' },
  rw: { label: 'Rwanda', phone: '250' },
  sa: { label: 'Saudi Arabia', phone: '966' },
  sb: { label: 'Solomon Islands', phone: '677' },
  sc: { label: 'Seychelles', phone: '248' },
  sd: { label: 'Sudan', phone: '249' },
  se: { label: 'Sweden', phone: '46' },
  sg: { label: 'Singapore', phone: '65' },
  sh: { label: 'Saint Helena', phone: '290' },
  si: { label: 'Slovenia', phone: '386' },
  sj: { label: 'Svalbard and Jan Mayen', phone: '47' },
  sk: { label: 'Slovakia', phone: '421' },
  sl: { label: 'Sierra Leone', phone: '232' },
  sm: { label: 'San Marino', phone: '378' },
  sn: { label: 'Senegal', phone: '221' },
  so: { label: 'Somalia', phone: '252' },
  sr: { label: 'Suriname', phone: '597' },
  ss: { label: 'South Sudan', phone: '211' },
  st: { label: 'Sao Tome and Principe', phone: '239' },
  sv: { label: 'El Salvador', phone: '503' },
  sx: { label: 'Sint Maarten (Dutch part)', phone: '1-721' },
  sy: { label: 'Syrian Arab Republic', phone: '963' },
  sz: { label: 'Swaziland', phone: '268' },
  tc: { label: 'Turks and Caicos Islands', phone: '1-649' },
  td: { label: 'Chad', phone: '235' },
  tf: { label: 'French Southern Territories', phone: '262' },
  tg: { label: 'Togo', phone: '228' },
  th: { label: 'Thailand', phone: '66' },
  tj: { label: 'Tajikistan', phone: '992' },
  tk: { label: 'Tokelau', phone: '690' },
  tl: { label: 'Timor Leste', phone: '670' },
  tm: { label: 'Turkmenistan', phone: '993' },
  tn: { label: 'Tunisia', phone: '216' },
  to: { label: 'Tonga', phone: '676' },
  tr: { label: 'Turkey', phone: '90' },
  tt: { label: 'Trinidad and Tobago', phone: '1-868' },
  tv: { label: 'Tuvalu', phone: '688' },
  tw: { label: 'Taiwan', phone: '886' },
  tz: { label: 'United Republic of Tanzania', phone: '255' },
  ua: { label: 'Ukraine', phone: '380' },
  ug: { label: 'Uganda', phone: '256' },
  us: { label: 'United States', phone: '1' },
  uy: { label: 'Uruguay', phone: '598' },
  uz: { label: 'Uzbekistan', phone: '998' },
  va: { label: 'Holy See (Vatican City State)', phone: '379' },
  vc: { label: 'Saint Vincent and the Grenadines', phone: '1-784' },
  ve: { label: 'Venezuela', phone: '58' },
  vg: { label: 'British Virgin Islands', phone: '1-284' },
  vi: { label: 'US Virgin Islands', phone: '1-340' },
  vn: { label: 'Vietnam', phone: '84' },
  vu: { label: 'Vanuatu', phone: '678' },
  wf: { label: 'Wallis and Futuna', phone: '681' },
  ws: { label: 'Samoa', phone: '685' },
  xk: { label: 'Kosovo', phone: '383' },
  ye: { label: 'Yemen', phone: '967' },
  yt: { label: 'Mayotte', phone: '262' },
  za: { label: 'South Africa', phone: '27' },
  zm: { label: 'Zambia', phone: '260' },
  zw: { label: 'Zimbabwe', phone: '263' },
}
