---
apiVersion: v1
kind: Service
metadata:
  name: moonshot-service
  namespace: default
  labels:
    app: moonshot  # Adding this label ensures it matches the selector in the playbook
  annotations:
    cloud.google.com/neg: '{"ingress":true}'  
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: moonshot
  ports:
    - protocol: TCP
      port: {{ moonshot_service_port }}
      targetPort: {{ moonshot_target_port }}

