# DO NOT CHANGE!
---

- name: Destroy Google Kubernetes Engine Cluster
  gcp_container_cluster:
    name: ascn-cluster
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  register: cluster
  until: "cluster is not failed"
  delay: 30
  retries: 3

- name: Wait for the cluster to be deleted
  gcp_container_cluster_info:
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: cluster_info
  delay: 30
  retries: 5
  until: "'ascn-cluster' not in cluster_info.resources | map(attribute='name') | list"
