# DO NOT CHANGE!
---

- name: Create GKE Cluster
  gcp_container_cluster:
    name: ascn-cluster
    initial_node_count: "{{ gcp_initial_node_count }}"
    node_config:
      machine_type: "{{ gcp_machine_type }}"
      disk_size_gb: "{{ gcp_disk_size_gb }}"
      image_type: "{{ gcp_image_type }}"
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: cluster

- name: Wait for cluster to be in RUNNING
  gcp_container_cluster_info:
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: cluster_info
  delay: 30
  retries: 5
  until: ("RUNNING" in cluster_info.resources | selectattr('name','==', 'ascn-cluster') | map(attribute='status'))


- name: Create a node pool
  gcp_container_node_pool:
    name: default-pool
    initial_node_count: "{{ gcp_initial_node_count }}"
    cluster: "{{ cluster }}"
    config:
      machine_type: "{{ gcp_machine_type }}"
      image_type: "{{ gcp_image_type }}"
      disk_size_gb: "{{ gcp_disk_size_gb }}"
    location: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: node_pool

- name: Connect to the cluster (update kubeconfig)"
  shell: gcloud container clusters get-credentials  --project="{{ gcp_project}}" --zone="{{ gcp_zone }}" ascn-cluster
