CREATE TABLE IF NOT EXISTS associate_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE, -- Added
    name text NOT NULL,
    description text NOT NULL,
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
);

-- Correct index from the start (Name is unique per tenant, not globally)
CREATE UNIQUE INDEX idx_associate_category_name_tenant_id_idx ON associate_category(name, tenant_id);
CREATE INDEX idx_associate_category_tenant_idx ON associate_category (tenant_id);