

CREATE TABLE IF NOT EXISTS
  accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL CHECK (
      email ~ '^[^,;@ \r\n]+@[^,@; \r\n]+\.[^,@; \r\n]+$'::text
    ),
    status_id integer NOT NULL DEFAULT 1 REFERENCES account_status (id),
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
  );

CREATE UNIQUE INDEX accounts_email_idx ON accounts (email);

CREATE INDEX accounts_status_idx ON accounts (status_id);


