CREATE TABLE IF NOT EXISTS subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint REFERENCES accounts(id) NOT NULL,
    tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE, -- Added
    price NUMERIC(7,2) NOT NULL,
    start_date timestamp(0) NOT NULL,
    end_date timestamp(0) NOT NULL,
    warning_sent_at timestamp(0), -- Added from the recent migration
    invoice_file text,
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
);

CREATE UNIQUE INDEX idx_account_id ON subscriptions(account_id);
CREATE INDEX idx_subscriptions_tenant_idx ON subscriptions (tenant_id);