
CREATE TABLE
  IF NOT EXISTS logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry jsonb,
    created_at timestamp(0) NOT NULL DEFAULT (NOW () at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW () at time zone ('utc'))
  );
