
CREATE TABLE
  IF NOT EXISTS storage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint REFERENCES accounts(id) NOT NULL,
    filename text NOT NULL,
    partition bigint NOT NULL,
    mime text NOT NULL,
    bytes bigint NOT NULL,
    created_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc')),
    updated_at timestamp(0) NOT NULL DEFAULT (NOW() at time zone ('utc'))
  );

CREATE INDEX storage_partition_idx ON storage (partition);
