---
- name: Execute PostgreSQL Deployment
  hosts: localhost
  gather_facts: false
  roles:
    - role: postgres
      vars:
        operation: "deploy"
        
- name: Execute Moonshot Deployment
  hosts: localhost
  gather_facts: false
  roles:
    - role: moonshot
      vars:
        operation: "deploy"
